import terminalIcon from './appIcons/terminal.png'
import mailIcon from './appIcons/mail.png'
import noteIcon from './appIcons/notes.png'
import javascriptIcon from './appIcons/javascript.png'
import reactIcon from './appIcons/react.png'
import reduxIcon from './appIcons/redux.png'
import htmlIcon from './appIcons/html.png'
import cssIcon from './appIcons/css.png'
import expressIcon from './appIcons/express.png'
import tailwindIcon from './appIcons/tailwind.png'
import mongodbIcon from './appIcons/mongodb.png'
import figmaIcon from './appIcons/figma.png'
import nodeIcon from './appIcons/node.png'
import viteIcon from './appIcons/vite.png'
import muiIcon from './appIcons/mui.png'
import storybookIcon from './appIcons/storybook.png'
import typescriptIcon from './appIcons/typescript.png'
import netlifyIcon from './appIcons/netlify.png'
import postmanIcon from './appIcons/postman.png'
import launchpadIcon from './appIcons/launchpad.png'
import appleLogo from './apple-logo.png'
import vpLogo from './vp-logo.svg'
import armeeLogo from './armee-logo.svg'
import linkedinIcon from './appIcons/linkedin.png'
import chevron from './chevron-droit.png'



export {terminalIcon, mailIcon, noteIcon, launchpadIcon, appleLogo, reactIcon, nodeIcon, typescriptIcon, javascriptIcon, reduxIcon, htmlIcon, cssIcon, tailwindIcon, mongodbIcon, figmaIcon, expressIcon, viteIcon, muiIcon, storybookIcon, netlifyIcon, postmanIcon, vpLogo, armeeLogo, linkedinIcon, chevron}